name: buildx

on:
  push:
    branches:
      - 'master'

env:
  GO111MODULE: on
  IMAGE: "neur0toxine/zabbix-metrics-mock:latest"
  PLATFORMS: "linux/amd64,linux/arm64,linux/386"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Available platforms
        run: echo ${{ env.PLATFORMS }}
      - name: Docker Buildx (build)
        uses: docker/build-push-action@v3.2.0
        if: success() && !contains(github.ref, 'master')
        with:
          push: false
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.IMAGE }}
      - name: Docker Login
        if: success() && contains(github.ref, 'master')
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Buildx (push)
        uses: docker/build-push-action@v3.2.0
        if: success() && contains(github.ref, 'master')
        with:
          push: true
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.IMAGE }}
      - name: Clear
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json
